library(XML)

#species 02:Picea abies, 00:Abies alba, 17:Fagus sylvatica, 09:Acer pseudoplatanus, 13:Betula pendula, 05:Pinus sylvestris,
#23:Quercus robur, 27:Tilia cordata, 01:Larix decidua, 25:Sorbus aria
def_species <- c("02", "00", "17", "09", "13", "05", "23", "27", "01", "25")

####setup of current climate########################################################################################### 
setupxml <- xmlTreeParse("c:/data/nawi/ws_2020/I3_project/forclim/orginal/SampleData4.0.1/ForClim_Setup.xml")
root_setup       <- xmlRoot(setupxml)

# create ForClim v4.0.1 sitefile and save
setup <- xmlOutputDOM("configData")
setup$addTag("version", "4.0.1") 
setup$addTag("siteParam", close=FALSE)
setup$addTag("name", "Site.xml")
setup$addTag("path", "Data/Sites/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[3]])  #copy species parametrisation tag 
setup$addTag("climateParam", close=FALSE)
setup$addTag("isCC", "False")
setup$addTag("name", "seasonalCC.xml")
setup$addTag("path", "Data/Climate/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[5]])  #copy snow modul tag 
setup$addTag("modelStructure", close=FALSE)
setup$addTag("variant", "14")                #variant=24: Establishment E6*(higher recruitment of shade tolerant species), Growth A2(stronger hight growth of shade tolerant species), background mortality M1(for natural forest development)
setup$closeTag()
setup$addTag("weatherParam", close=FALSE)
setup$addTag("isWeatherInput", "False")
setup$addTag("name", "weather.xml")
setup$addTag("path", "Data/Weather/")
setup$closeTag()
setup$addTag("managementParam", close=FALSE)
setup$addTag("isHarvest", "False")
setup$addTag("name", "Management.xml")
setup$addTag("path", "Data/Management/")
setup$closeTag()
setup$addTag("states", close=FALSE)
setup$addTag("name", "stand_terfens.xml")
setup$addTag("path", "Data/States/")
setup$addTag("standDataIn", "True")         #initialisation with stand data
setup$addTag("stateIn", "False")
setup$addTag("stateOut", "False")
setup$closeTag()
setup$addTag("results", close=FALSE)
setup$addTag("name", "CurrentClimate")       #define model run
setup$addTag("path", "output/")
setup$addTag("cohortOut", "False")
setup$addTag("logDIncOut", "False")
setup$addTag("limFactOut", "True")
setup$addTag("cohortsSQLiteOut", "True")
setup$closeTag()
setup$addTag("simulation", close=FALSE)
setup$addTag("name", "Terfens")
setup$addTag("initTime", "2020")
setup$addTag("endTime", "2100")
setup$addTag("runNumber", "200")
setup$addTag("viewStep", "1")
setup$addTag("viewStepSQL", "1")
setup$addTag("startOutput", "0")
setup$addTag("seedValue", "1")
setup$closeTag()
setup$addTag("output", close=FALSE)
setup$addTag("disable", "False")
setup$closeTag()
for (i in 1:length(def_species)) {     #insert spcies to xml
  setup$addTag("actualSpecies", close=FALSE)
  setup$addTag("kID", def_species[i])
  setup$closeTag()
}
setup$closeTag()

saveXML(setup$value(), file=paste("c:/data/nawi/ws_2020/I3_project/forclim/setup_cc/ForClim_Setup_cc.xml"))
saveXML(setup$value(), file=paste("c:/eigene_programme/ForClim/ForClim_Setup.xml"))

####setup of RCP 4.5 ########################################################################################### 
setupxml <- xmlTreeParse("c:/data/nawi/ws_2020/I3_project/forclim/orginal/SampleData4.0.1/ForClim_Setup.xml")
root_setup       <- xmlRoot(setupxml)

# create ForClim v4.0.1 sitefile and save
setup <- xmlOutputDOM("configData")
setup$addTag("version", "4.0.1") 
setup$addTag("siteParam", close=FALSE)
setup$addTag("name", "Site.xml")
setup$addTag("path", "Data/Sites/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[3]])  #copy species parametrisation tag 
setup$addTag("climateParam", close=FALSE)
setup$addTag("isCC", "True")
setup$addTag("name", "seasonalCC.xml")
setup$addTag("path", "Data/Climate/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[5]])  #copy snow modul tag 
setup$addTag("modelStructure", close=FALSE)
setup$addTag("variant", "14")                #variant=24: Establishment E6*(higher recruitment of shade tolerant species), Growth A2(stronger hight growth of shade tolerant species), background mortality M1(for natural forest development)
setup$closeTag()
setup$addTag("weatherParam", close=FALSE)
setup$addTag("isWeatherInput", "False")
setup$addTag("name", "weather.xml")
setup$addTag("path", "Data/Weather/")
setup$closeTag()
setup$addTag("managementParam", close=FALSE)
setup$addTag("isHarvest", "False")
setup$addTag("name", "Management.xml")
setup$addTag("path", "Data/Management/")
setup$closeTag()
setup$addTag("states", close=FALSE)
setup$addTag("name", "stand_terfens.xml")
setup$addTag("path", "Data/States/")
setup$addTag("standDataIn", "True")         #initialisation with stand data
setup$addTag("stateIn", "False")
setup$addTag("stateOut", "False")
setup$closeTag()
setup$addTag("results", close=FALSE)
setup$addTag("name", "rcp45")              #define model run
setup$addTag("path", "output/")
setup$addTag("cohortOut", "False")
setup$addTag("logDIncOut", "False")
setup$addTag("limFactOut", "True")
setup$addTag("cohortsSQLiteOut", "True")
setup$closeTag()
setup$addTag("simulation", close=FALSE)
setup$addTag("name", "Terfens")
setup$addTag("initTime", "2020")
setup$addTag("endTime", "2100")
setup$addTag("runNumber", "200")
setup$addTag("viewStep", "1")
setup$addTag("viewStepSQL", "1")
setup$addTag("startOutput", "0")
setup$addTag("seedValue", "1")
setup$closeTag()
setup$addTag("output", close=FALSE)
setup$addTag("disable", "False")
setup$closeTag()
for (i in 1:length(def_species)) {     #insert spcies to xml
  setup$addTag("actualSpecies", close=FALSE)
  setup$addTag("kID", def_species[i])
  setup$closeTag()
}
setup$closeTag()

saveXML(setup$value(), file=paste("c:/data/nawi/ws_2020/I3_project/forclim/setup_rcp45/ForClim_Setup_rcp45.xml"))
saveXML(setup$value(), file=paste("c:/eigene_programme/ForClim/ForClim_Setup.xml"))

####setup of RCP 8.5########################################################################################### 
setupxml <- xmlTreeParse("c:/data/nawi/ws_2020/I3_project/forclim/orginal/SampleData4.0.1/ForClim_Setup.xml")
root_setup       <- xmlRoot(setupxml)

# create ForClim v4.0.1 sitefile and save
setup <- xmlOutputDOM("configData")
setup$addTag("version", "4.0.1") 
setup$addTag("siteParam", close=FALSE)
setup$addTag("name", "Site.xml")
setup$addTag("path", "Data/Sites/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[3]])  #copy species parametrisation tag 
setup$addTag("climateParam", close=FALSE)
setup$addTag("isCC", "True")                 #apply climate change szenarios 
setup$addTag("name", "seasonalCC.xml")
setup$addTag("path", "Data/Climate/")
setup$closeTag()
setup$addNode(xmlChildren(root_setup)[[5]])  #copy snow modul tag 
setup$addTag("modelStructure", close=FALSE)
setup$addTag("variant", "14")                #variant=24: Establishment E6*(higher recruitment of shade tolerant species), Growth A2(stronger hight growth of shade tolerant species), background mortality M1(for natural forest development)
setup$closeTag()
setup$addTag("weatherParam", close=FALSE)
setup$addTag("isWeatherInput", "False")
setup$addTag("name", "weather.xml")
setup$addTag("path", "Data/Weather/")
setup$closeTag()
setup$addTag("managementParam", close=FALSE)
setup$addTag("isHarvest", "False")
setup$addTag("name", "Management.xml")
setup$addTag("path", "Data/Management/")
setup$closeTag()
setup$addTag("states", close=FALSE)
setup$addTag("name", "stand_terfens.xml")
setup$addTag("path", "Data/States/")
setup$addTag("standDataIn", "True")         #initialisation with stand data
setup$addTag("stateIn", "False")
setup$addTag("stateOut", "False")
setup$closeTag()
setup$addTag("results", close=FALSE)
setup$addTag("name", "rcp85")       #define model run
setup$addTag("path", "output/")
setup$addTag("cohortOut", "False")
setup$addTag("logDIncOut", "False")
setup$addTag("limFactOut", "True")
setup$addTag("cohortsSQLiteOut", "True")
setup$closeTag()
setup$addTag("simulation", close=FALSE)
setup$addTag("name", "Terfens")
setup$addTag("initTime", "2020")
setup$addTag("endTime", "2100")
setup$addTag("runNumber", "200")
setup$addTag("viewStep", "1")
setup$addTag("viewStepSQL", "1")
setup$addTag("startOutput", "0")
setup$addTag("seedValue", "1")
setup$closeTag()
setup$addTag("output", close=FALSE)
setup$addTag("disable", "False")
setup$closeTag()
for (i in 1:length(def_species)) {     #insert spcies to xml
  setup$addTag("actualSpecies", close=FALSE)
  setup$addTag("kID", def_species[i])
  setup$closeTag()
}
setup$closeTag()

saveXML(setup$value(), file=paste("c:/data/nawi/ws_2020/I3_project/forclim/setup_rcp85/ForClim_Setup_rcp85.xml"))
saveXML(setup$value(), file=paste("c:/eigene_programme/ForClim/ForClim_Setup.xml"))


